#!/usr/bin/env python3
"""
ShiftGuard -- Synthetic Dataset Generator (Phase 1)
==================================================

DISCLAIMER:
All data generated by this script is 100% SYNTHETIC and generated programmatically
for demonstration, development, and testing of the ShiftGuard Operator Assistant.
It does NOT represent actual Caterpillar Inc. production data, telemetry, or machine records.

Usage:
    python scripts/generate_synthetic_data.py [--seed 42] [--output-dir data/synthetic]
"""

import argparse
import csv
import math
import os
from datetime import datetime, timedelta, timezone
from pathlib import Path
import random

# Default Deterministic Seed
DEFAULT_SEED = 42

# Fleet Definition for Synthetic Shift
MACHINES = [
    {
        "id": "CAT-797F-101",
        "model": "797F",
        "type": "Haul Truck",
        "age_years": 3.2,
        "base_engine_hours": 8420.5,
        "operator_id": "OP-101",
        "nominal_fuel_rate_lph": 75.0,
    },
    {
        "id": "CAT-797F-102",
        "model": "797F",
        "type": "Haul Truck",
        "age_years": 5.8,
        "base_engine_hours": 14210.0,
        "operator_id": "OP-102",
        "nominal_fuel_rate_lph": 82.0,
    },
    {
        "id": "CAT-6060-201",
        "model": "6060",
        "type": "Hydraulic Shovel",
        "age_years": 2.1,
        "base_engine_hours": 5120.2,
        "operator_id": "OP-103",
        "nominal_fuel_rate_lph": 110.0,
    },
    {
        "id": "CAT-994K-301",
        "model": "994K",
        "type": "Wheel Loader",
        "age_years": 4.0,
        "base_engine_hours": 9860.8,
        "operator_id": "OP-104",
        "nominal_fuel_rate_lph": 65.0,
    },
    {
        "id": "CAT-D11-401",
        "model": "D11",
        "type": "Track Dozer",
        "age_years": 6.5,
        "base_engine_hours": 16480.0,
        "operator_id": "OP-105",
        "nominal_fuel_rate_lph": 70.0,
    },
]

OPERATORS = [
    {"id": "OP-101", "name": "OPERATOR 1", "skill": "EXPERT"},
    {"id": "OP-102", "name": "OPERATOR 2", "skill": "INTERMEDIATE"},
    {"id": "OP-103", "name": "OPERATOR 3", "skill": "EXPERT"},
    {"id": "OP-104", "name": "OPERATOR 4", "skill": "NOVICE"},
    {"id": "OP-105", "name": "OPERATOR 5", "skill": "INTERMEDIATE"},
]

GPS_ZONES = [
    "PIT_FLOOR_BENCH_A",
    "PIT_FLOOR_BENCH_B",
    "HAUL_ROAD_NORTH",
    "HAUL_ROAD_SOUTH",
    "CRUSHER_FEED_1",
    "OVERBURDEN_DUMP_WEST",
    "RAMP_ACCESS_EAST",
    "STAGING_BAY_4",
]

TASK_TYPES = [
    "OVERBURDEN_REMOVAL",
    "ORE_HAULING",
    "BENCH_CLEANUP",
    "STOCKPILE_FEEDING",
    "RAMP_MAINTENANCE",
]

WEATHER_CONDITIONS = [
    "CLEAR",
    "DUSTY",
    "RAIN",
    "MUDDY_GROUND",
    "FOG",
    "HIGH_WIND",
]

WORKING_CONDITIONS = [
    "NORMAL",
    "MODERATE",
    "SEVERE",
    "MUDDY",
    "STEEP_INCLINE",
]


def ensure_directories(base_dir: Path):
    """Ensure raw, processed, and synthetic directories exist."""
    (base_dir / "raw").mkdir(parents=True, exist_ok=True)
    (base_dir / "processed").mkdir(parents=True, exist_ok=True)
    (base_dir / "synthetic").mkdir(parents=True, exist_ok=True)
    
    # Touch .gitkeep files in raw and processed if empty
    for folder in ["raw", "processed"]:
        keep_file = base_dir / folder / ".gitkeep"
        if not keep_file.exists():
            keep_file.touch()


def generate_task_history(rng: random.Random, num_tasks: int = 150) -> list[dict]:
    """
    Generate realistic task history records with causal correlations
    between conditions, operator skill, machine age, and completion time.
    """
    tasks = []
    base_time = datetime(2026, 9, 20, 6, 0, 0, tzinfo=timezone.utc)
    
    # Skill multipliers on duration (Expert completes faster, Novice takes longer)
    skill_impact = {
        "EXPERT": -0.07,
        "INTERMEDIATE": 0.02,
        "NOVICE": 0.16,
    }
    
    # Weather multipliers on duration
    weather_impact = {
        "CLEAR": 0.0,
        "DUSTY": 0.03,
        "HIGH_WIND": 0.06,
        "FOG": 0.12,
        "RAIN": 0.15,
        "MUDDY_GROUND": 0.22,
    }
    
    # Condition multipliers on duration
    condition_impact = {
        "NORMAL": 0.0,
        "MODERATE": 0.05,
        "STEEP_INCLINE": 0.14,
        "SEVERE": 0.18,
        "MUDDY": 0.24,
    }

    for i in range(1, num_tasks + 1):
        task_id = f"TSK-{1000 + i}"
        machine = rng.choice(MACHINES)
        operator = next(op for op in OPERATORS if op["id"] == machine["operator_id"])
        task_type = rng.choice(TASK_TYPES)
        weather = rng.choice(WEATHER_CONDITIONS)
        condition = rng.choice(WORKING_CONDITIONS)
        
        # Base estimated duration between 40.0 and 110.0 minutes
        estimated_time_min = round(rng.uniform(40.0, 110.0), 1)
        
        # Causal multipliers
        skill_factor = skill_impact[operator["skill"]]
        weather_factor = weather_impact[weather]
        condition_factor = condition_impact[condition]
        age_factor = (machine["age_years"] * 0.015)  # +1.5% per year of age
        random_noise = rng.uniform(-0.03, 0.03)  # Small realistic variance (+/- 3%)
        
        total_multiplier = 1.0 + skill_factor + weather_factor + condition_factor + age_factor + random_noise
        actual_time_min = round(max(estimated_time_min * 0.75, estimated_time_min * total_multiplier), 1)
        
        # Time scheduling
        task_offset_minutes = (i - 1) * 25 + rng.randint(0, 10)
        planned_start = base_time + timedelta(minutes=task_offset_minutes)
        # Dispatch delay 0 to 6 minutes
        dispatch_delay = rng.randint(0, 6)
        actual_start = planned_start + timedelta(minutes=dispatch_delay)
        
        tasks.append({
            "task_id": task_id,
            "machine_id": machine["id"],
            "operator_id": operator["id"],
            "task_type": task_type,
            "weather": weather,
            "operator_skill": operator["skill"],
            "machine_age_years": machine["age_years"],
            "estimated_time_min": estimated_time_min,
            "actual_time_min": actual_time_min,
            "planned_start": planned_start.isoformat().replace("+00:00", "Z"),
            "actual_start": actual_start.isoformat().replace("+00:00", "Z"),
            "working_condition": condition,
        })
        
    return tasks


def generate_telemetry_history(rng: random.Random, tasks: list[dict], duration_hours: float = 8.0, step_seconds: int = 45) -> list[dict]:
    """
    Generate realistic, chronologically ordered telemetry time-series for 5 machines.
    All physics and internal correlations are maintained:
    - stopped -> speed 0, low/zero rpm, 0 load
    - idle -> speed 0, idle rpm (650-750), idle load (10-18%)
    - travelling -> speed 18-42 km/h, rpm 1400-1850, load 40-70%
    - working/digging -> speed 0-3 km/h, rpm 1700-2100, load 75-95%
    - fuel consumption accumulates monotonically based on load & model
    - engine hours accumulate monotonically
    - load cycles accumulate monotonically
    """
    records = []
    start_time = datetime(2026, 9, 20, 6, 0, 0, tzinfo=timezone.utc)
    total_steps = int((duration_hours * 3600) // step_seconds)
    
    # Track persistent machine state
    machine_states = {}
    for m in MACHINES:
        machine_states[m["id"]] = {
            "engine_hours": m["base_engine_hours"],
            "fuel_used_l": 0.0,
            "idling_time_min": 0.0,
            "load_cycles": 0,
            "coolant_temp_c": 82.5 + rng.uniform(-1.0, 1.0),
            "hydraulic_temp_c": 68.0 + rng.uniform(-2.0, 2.0),
            "state_timer_remaining": 0,
            "current_state": "HAULING_EMPTY" if "797F" in m["id"] else "EXCAVATING",
            "current_zone": "HAUL_ROAD_NORTH",
            "current_task_idx": 0,
        }
        
    # Cycle progression state machine for haul trucks
    haul_truck_cycle = ["HAULING_EMPTY", "SPOTTING", "LOADING", "HAULING_LOADED", "DUMPING"]
    # Durations in steps for each phase (step = 45s)
    phase_durations = {
        "HAULING_EMPTY": (8, 14),   # ~6-10 min travel
        "SPOTTING": (1, 2),         # ~45-90s spot
        "LOADING": (3, 6),          # ~2-4.5 min load
        "HAULING_LOADED": (9, 16),  # ~7-12 min travel loaded
        "DUMPING": (2, 3),          # ~1.5-2.2 min dump
        "IDLE": (2, 5),             # Staging/queue
        "STOPPED": (2, 4),          # Shift check
        "EXCAVATING": (8, 20),      # Shovel continuous
        "DOZING": (8, 18),          # Dozer continuous
    }

    # Group tasks by machine for consistent task_id linkage
    tasks_by_machine = {}
    for t in tasks:
        tasks_by_machine.setdefault(t["machine_id"], []).append(t)

    for step in range(total_steps):
        current_timestamp = start_time + timedelta(seconds=step * step_seconds)
        iso_timestamp = current_timestamp.isoformat().replace("+00:00", "Z")
        
        for m in MACHINES:
            m_id = m["id"]
            state = machine_states[m_id]
            
            # Associate active task
            m_tasks = tasks_by_machine.get(m_id, [])
            current_task = m_tasks[state["current_task_idx"] % len(m_tasks)] if m_tasks else None
            task_id = current_task["task_id"] if current_task else "TSK-1001"
            working_condition = current_task["working_condition"] if current_task else "NORMAL"
            
            # State transitions
            if state["state_timer_remaining"] <= 0:
                is_truck = "797F" in m_id
                if is_truck:
                    cur = state["current_state"]
                    if cur in haul_truck_cycle:
                        next_idx = (haul_truck_cycle.index(cur) + 1) % len(haul_truck_cycle)
                        # Rare chance to transition into brief IDLE
                        if next_idx == 0 and rng.random() < 0.15:
                            next_state = "IDLE"
                        else:
                            next_state = haul_truck_cycle[next_idx]
                            if cur == "DUMPING":
                                state["load_cycles"] += 1
                                # Advance task occasionally
                                state["current_task_idx"] = (state["current_task_idx"] + 1) % max(1, len(m_tasks))
                    elif cur == "IDLE":
                        next_state = "HAULING_EMPTY"
                    else:
                        next_state = "HAULING_EMPTY"
                elif "6060" in m_id:
                    next_state = rng.choices(["EXCAVATING", "IDLE", "SPOTTING"], weights=[0.82, 0.12, 0.06])[0]
                    if next_state == "EXCAVATING" and state["current_state"] != "EXCAVATING":
                        state["load_cycles"] += 1
                elif "994K" in m_id:
                    next_state = rng.choices(["LOADING", "HAULING_LOADED", "IDLE"], weights=[0.75, 0.18, 0.07])[0]
                    if next_state == "LOADING" and state["current_state"] != "LOADING":
                        state["load_cycles"] += 1
                else:  # CAT-D11 Dozer
                    next_state = rng.choices(["DOZING", "IDLE", "STOPPED"], weights=[0.80, 0.15, 0.05])[0]
                    if next_state == "DOZING" and state["current_state"] != "DOZING":
                        state["load_cycles"] += 1
                
                state["current_state"] = next_state
                d_min, d_max = phase_durations.get(next_state, (3, 6))
                state["state_timer_remaining"] = rng.randint(d_min, d_max)
                
                # Zone update according to state
                if next_state in ["HAULING_EMPTY", "HAULING_LOADED"]:
                    state["current_zone"] = rng.choice(["HAUL_ROAD_NORTH", "HAUL_ROAD_SOUTH", "RAMP_ACCESS_EAST"])
                elif next_state in ["LOADING", "EXCAVATING"]:
                    state["current_zone"] = rng.choice(["PIT_FLOOR_BENCH_A", "PIT_FLOOR_BENCH_B"])
                elif next_state == "DUMPING":
                    state["current_zone"] = "OVERBURDEN_DUMP_WEST"
                elif next_state == "SPOTTING":
                    state["current_zone"] = "CRUSHER_FEED_1"
                else:
                    state["current_zone"] = "STAGING_BAY_4"
            else:
                state["state_timer_remaining"] -= 1

            current_st = state["current_state"]
            
            # Physics & sensor values by state
            if current_st == "STOPPED":
                rpm = 0.0
                load_pct = 0.0
                speed_kmh = 0.0
                proximity = round(rng.uniform(15.0, 35.0), 1)
                fuel_rate_factor = 0.0
                hours_increment = 0.0
            elif current_st == "IDLE":
                rpm = round(rng.uniform(680.0, 740.0), 1)
                load_pct = round(rng.uniform(10.0, 16.0), 1)
                speed_kmh = 0.0
                proximity = round(rng.uniform(14.0, 28.0), 1)
                fuel_rate_factor = 0.20  # ~20% of nominal fuel
                state["idling_time_min"] += (step_seconds / 60.0)
                hours_increment = (step_seconds / 3600.0)
            elif current_st in ["SPOTTING", "DUMPING"]:
                rpm = round(rng.uniform(1100.0, 1380.0), 1)
                load_pct = round(rng.uniform(32.0, 48.0), 1)
                speed_kmh = round(rng.uniform(0.5, 3.2), 1)
                proximity = round(rng.uniform(6.5, 14.0), 1)
                fuel_rate_factor = 0.55
                hours_increment = (step_seconds / 3600.0)
            elif current_st == "LOADING":
                rpm = round(rng.uniform(1450.0, 1750.0), 1)
                load_pct = round(rng.uniform(55.0, 75.0), 1)
                speed_kmh = round(rng.uniform(0.0, 1.2), 1)
                proximity = round(rng.uniform(6.0, 11.0), 1)
                fuel_rate_factor = 0.70
                hours_increment = (step_seconds / 3600.0)
            elif current_st == "HAULING_EMPTY":
                rpm = round(rng.uniform(1500.0, 1820.0), 1)
                load_pct = round(rng.uniform(42.0, 62.0), 1)
                speed_kmh = round(rng.uniform(24.0, 41.5), 1)
                proximity = round(rng.uniform(22.0, 55.0), 1)
                fuel_rate_factor = 0.75
                hours_increment = (step_seconds / 3600.0)
            elif current_st == "HAULING_LOADED":
                rpm = round(rng.uniform(1700.0, 1950.0), 1)
                load_pct = round(rng.uniform(72.0, 92.0), 1)
                # Slower speed when loaded or steep
                speed_kmh = round(rng.uniform(16.0, 28.5), 1)
                if working_condition == "STEEP_INCLINE":
                    speed_kmh = max(8.0, speed_kmh - 8.0)
                    load_pct = min(98.0, load_pct + 8.0)
                proximity = round(rng.uniform(20.0, 48.0), 1)
                fuel_rate_factor = 1.15
                hours_increment = (step_seconds / 3600.0)
            elif current_st in ["EXCAVATING", "DOZING"]:
                rpm = round(rng.uniform(1750.0, 2050.0), 1)
                load_pct = round(rng.uniform(75.0, 94.0), 1)
                speed_kmh = round(rng.uniform(1.0, 5.0), 1)
                proximity = round(rng.uniform(8.0, 22.0), 1)
                fuel_rate_factor = 1.05
                hours_increment = (step_seconds / 3600.0)
            else:
                rpm = 1200.0
                load_pct = 40.0
                speed_kmh = 10.0
                proximity = 25.0
                fuel_rate_factor = 0.5
                hours_increment = (step_seconds / 3600.0)

            # Monotonic accumulations
            state["engine_hours"] += hours_increment
            step_fuel_l = (m["nominal_fuel_rate_lph"] * fuel_rate_factor) * (step_seconds / 3600.0)
            state["fuel_used_l"] += step_fuel_l
            
            # Thermal dynamics
            target_coolant = 82.0 + (load_pct / 100.0) * 14.0
            if working_condition in ["SEVERE", "MUDDY"]:
                target_coolant += 3.5
            state["coolant_temp_c"] += (target_coolant - state["coolant_temp_c"]) * 0.08
            
            target_hyd = 66.0 + (load_pct / 100.0) * 16.0
            state["hydraulic_temp_c"] += (target_hyd - state["hydraulic_temp_c"]) * 0.05
            
            # Seatbelt status (99.8% fastened in normal baseline)
            seatbelt = "FASTENED" if rng.random() > 0.002 else "UNFASTENED"
            
            # Fault codes (Rare, realistic transient warnings)
            fault = "NONE"
            if state["coolant_temp_c"] > 96.5 and rng.random() < 0.05:
                fault = "ENG-TEMP-HIGH-01"
            elif proximity < 7.0 and current_st not in ["LOADING", "SPOTTING"] and rng.random() < 0.04:
                fault = "PRX-WARN-CLOSE-02"

            records.append({
                "timestamp": iso_timestamp,
                "machine_id": m_id,
                "operator_id": m["operator_id"],
                "engine_hours": round(state["engine_hours"], 2),
                "engine_rpm": round(rpm, 1),
                "engine_load_pct": round(load_pct, 1),
                "machine_speed_kmh": round(speed_kmh, 1),
                "fuel_used_l": round(state["fuel_used_l"], 2),
                "idling_time_min": round(state["idling_time_min"], 1),
                "load_cycles": int(state["load_cycles"]),
                "operating_state": current_st,
                "seatbelt_status": seatbelt,
                "proximity_distance_m": round(proximity, 1),
                "gps_zone": state["current_zone"],
                "working_condition": working_condition,
                "coolant_temp_c": round(state["coolant_temp_c"], 1),
                "hydraulic_oil_temp_c": round(state["hydraulic_temp_c"], 1),
                "fault_code": fault,
                "task_id": task_id,
            })
            
    return records


def generate_demo_telemetry() -> list[dict]:
    """
    Generate deterministic, hand-crafted demo sequences for judging / test scenarios.
    Does NOT rely on random runtime behavior.
    Includes explicit sequences for:
    1. Normal operation
    2. Seatbelt violation while machine is moving
    3. Proximity warning (approaching threshold)
    4. Proximity critical (imminent hazard threshold)
    5. Excessive idle accumulation
    6. Repeated safety behavior (unbuckle + proximity violation)
    7. Delayed task (muddy / incline drag)
    """
    records = []
    base_time = datetime(2026, 9, 21, 10, 0, 0, tzinfo=timezone.utc)
    step_delta = timedelta(seconds=15)
    
    current_time = base_time
    def next_time():
        nonlocal current_time
        t_str = current_time.isoformat().replace("+00:00", "Z")
        current_time += step_delta
        return t_str

    # -------------------------------------------------------------
    # Scenario 1: Normal Operation (16 dynamic steps)
    # Haul truck moving along haul road with dynamic speed, RPM, load, proximity
    # -------------------------------------------------------------
    norm_speeds = [26.5, 28.2, 30.5, 32.8, 34.2, 35.0, 33.6, 31.8, 30.2, 29.0, 31.5, 33.2, 34.6, 35.2, 33.8, 32.5]
    norm_rpms = [1520.0, 1580.0, 1640.0, 1710.0, 1740.0, 1760.0, 1690.0, 1630.0, 1590.0, 1560.0, 1650.0, 1720.0, 1750.0, 1780.0, 1700.0, 1660.0]
    norm_loads = [54.0, 58.5, 62.0, 65.5, 67.0, 68.5, 64.0, 61.2, 59.0, 57.5, 63.0, 66.5, 68.0, 69.2, 65.0, 62.5]
    norm_proxs = [45.0, 42.5, 39.0, 36.5, 34.0, 32.5, 35.0, 38.5, 41.0, 43.5, 40.0, 37.2, 35.0, 38.0, 42.0, 44.5]
    norm_coolants = [85.8, 86.0, 86.2, 86.5, 86.8, 87.0, 87.1, 86.9, 86.7, 86.5, 86.8, 87.0, 87.2, 87.4, 87.2, 87.0]

    for i in range(16):
        records.append({
            "timestamp": next_time(),
            "machine_id": "CAT-797F-101",
            "operator_id": "OP-101",
            "engine_hours": round(8430.00 + i * 0.004, 2),
            "engine_rpm": norm_rpms[i],
            "engine_load_pct": norm_loads[i],
            "machine_speed_kmh": norm_speeds[i],
            "fuel_used_l": round(45.20 + i * 0.32, 2),
            "idling_time_min": 12.0,
            "load_cycles": 14 if i < 10 else 15,
            "operating_state": "HAULING_LOADED",
            "seatbelt_status": "FASTENED",
            "proximity_distance_m": norm_proxs[i],
            "gps_zone": "HAUL_ROAD_NORTH",
            "working_condition": "NORMAL" if i < 12 else "OPTIMAL",
            "coolant_temp_c": norm_coolants[i],
            "hydraulic_oil_temp_c": round(71.8 + i * 0.06, 1),
            "fault_code": "NONE",
            "task_id": "TSK-DEMO-01",
        })

    # -------------------------------------------------------------
    # Scenario 2: Seatbelt Violation (7 steps)
    # Machine travelling at 26 km/h with UNFASTENED seatbelt
    # -------------------------------------------------------------
    for i in range(7):
        records.append({
            "timestamp": next_time(),
            "machine_id": "CAT-797F-101",
            "operator_id": "OP-101",
            "engine_hours": round(8430.04 + i * 0.004, 2),
            "engine_rpm": 1620.0,
            "engine_load_pct": 58.0,
            "machine_speed_kmh": 26.0,
            "fuel_used_l": round(48.00 + i * 0.32, 2),
            "idling_time_min": 12.0,
            "load_cycles": 14,
            "operating_state": "HAULING_LOADED",
            "seatbelt_status": "UNFASTENED",
            "proximity_distance_m": 38.0,
            "gps_zone": "HAUL_ROAD_NORTH",
            "working_condition": "NORMAL",
            "coolant_temp_c": 86.8,
            "hydraulic_oil_temp_c": 72.5,
            "fault_code": "SEC-SBLT-WARN",
            "task_id": "TSK-DEMO-02",
        })

    # -------------------------------------------------------------
    # Scenario 3: Proximity Warning (6 steps)
    # Distance drops from 15m to 8.2m while moving
    # -------------------------------------------------------------
    distances_warn = [15.2, 12.5, 10.1, 8.8, 8.2, 8.4]
    for i, dist in enumerate(distances_warn):
        records.append({
            "timestamp": next_time(),
            "machine_id": "CAT-797F-102",
            "operator_id": "OP-102",
            "engine_hours": round(14218.10 + i * 0.004, 2),
            "engine_rpm": 1350.0,
            "engine_load_pct": 44.0,
            "machine_speed_kmh": 14.0,
            "fuel_used_l": round(62.10 + i * 0.25, 2),
            "idling_time_min": 8.0,
            "load_cycles": 11,
            "operating_state": "SPOTTING",
            "seatbelt_status": "FASTENED",
            "proximity_distance_m": dist,
            "gps_zone": "CRUSHER_FEED_1",
            "working_condition": "MODERATE",
            "coolant_temp_c": 88.0,
            "hydraulic_oil_temp_c": 74.0,
            "fault_code": "PRX-WARN-AMBER",
            "task_id": "TSK-DEMO-03",
        })

    # -------------------------------------------------------------
    # Scenario 4: Proximity Critical (6 steps)
    # Obstacle distance drops sharply to 2.8m, emergency stop initiated
    # -------------------------------------------------------------
    crit_steps = [
        (6.5, 11.0, 1200.0, "PRX-WARN-AMBER"),
        (4.2, 7.0, 1000.0, "PRX-CRIT-RED"),
        (2.8, 2.0, 850.0, "PRX-CRIT-RED"),
        (2.8, 0.0, 720.0, "PRX-CRIT-STOP"),
        (2.8, 0.0, 720.0, "PRX-CRIT-STOP"),
        (3.5, 0.0, 720.0, "PRX-CRIT-STOP"),
    ]
    for i, (dist, spd, rpm, flt) in enumerate(crit_steps):
        records.append({
            "timestamp": next_time(),
            "machine_id": "CAT-797F-102",
            "operator_id": "OP-102",
            "engine_hours": round(14218.13 + i * 0.004, 2),
            "engine_rpm": rpm,
            "engine_load_pct": 20.0 if spd == 0.0 else 40.0,
            "machine_speed_kmh": spd,
            "fuel_used_l": round(63.80 + i * 0.15, 2),
            "idling_time_min": 8.0 + (i * 0.25 if spd == 0.0 else 0.0),
            "load_cycles": 11,
            "operating_state": "IDLE" if spd == 0.0 else "SPOTTING",
            "seatbelt_status": "FASTENED",
            "proximity_distance_m": dist,
            "gps_zone": "CRUSHER_FEED_1",
            "working_condition": "MODERATE",
            "coolant_temp_c": 89.2,
            "hydraulic_oil_temp_c": 75.1,
            "fault_code": flt,
            "task_id": "TSK-DEMO-04",
        })

    # -------------------------------------------------------------
    # Scenario 5: Excessive Idle (8 steps)
    # Machine parked with engine running, idle counter surging past 25 min
    # -------------------------------------------------------------
    for i in range(8):
        idle_accum = round(24.5 + i * 1.5, 1)
        records.append({
            "timestamp": next_time(),
            "machine_id": "CAT-994K-301",
            "operator_id": "OP-104",
            "engine_hours": round(9870.50 + i * 0.004, 2),
            "engine_rpm": 710.0,
            "engine_load_pct": 12.5,
            "machine_speed_kmh": 0.0,
            "fuel_used_l": round(38.40 + i * 0.08, 2),
            "idling_time_min": idle_accum,
            "load_cycles": 8,
            "operating_state": "IDLE",
            "seatbelt_status": "FASTENED",
            "proximity_distance_m": 22.0,
            "gps_zone": "STAGING_BAY_4",
            "working_condition": "NORMAL",
            "coolant_temp_c": 81.2,
            "hydraulic_oil_temp_c": 64.5,
            "fault_code": "IDL-EXCESS-WARN" if idle_accum >= 28.0 else "NONE",
            "task_id": "TSK-DEMO-05",
        })

    # -------------------------------------------------------------
    # Scenario 6: Repeated Safety Behavior (8 steps)
    # Operator unfastens seatbelt then tailgates another vehicle within 2 minutes
    # -------------------------------------------------------------
    repeat_safety = [
        ("UNFASTENED", 32.0, 24.0, "SEC-SBLT-WARN"),
        ("UNFASTENED", 28.0, 22.0, "SEC-SBLT-WARN"),
        ("FASTENED", 25.0, 16.0, "NONE"),
        ("FASTENED", 22.0, 11.2, "PRX-WARN-AMBER"),
        ("FASTENED", 18.0, 7.4, "PRX-WARN-AMBER"),
        ("UNFASTENED", 14.0, 5.1, "PRX-CRIT-MULTI"),
        ("UNFASTENED", 0.0, 4.8, "PRX-CRIT-MULTI"),
        ("FASTENED", 0.0, 4.8, "SEC-SAFETY-STANDDOWN"),
    ]
    for i, (sblt, spd, dist, flt) in enumerate(repeat_safety):
        records.append({
            "timestamp": next_time(),
            "machine_id": "CAT-D11-401",
            "operator_id": "OP-105",
            "engine_hours": round(16492.20 + i * 0.004, 2),
            "engine_rpm": 1400.0 if spd > 0 else 720.0,
            "engine_load_pct": 52.0 if spd > 0 else 14.0,
            "machine_speed_kmh": spd,
            "fuel_used_l": round(55.60 + i * 0.22, 2),
            "idling_time_min": 4.0 if spd > 0 else 5.2,
            "load_cycles": 19,
            "operating_state": "DOZING" if spd > 0 else "IDLE",
            "seatbelt_status": sblt,
            "proximity_distance_m": dist,
            "gps_zone": "OVERBURDEN_DUMP_WEST",
            "working_condition": "SEVERE",
            "coolant_temp_c": 92.5,
            "hydraulic_oil_temp_c": 79.8,
            "fault_code": flt,
            "task_id": "TSK-DEMO-06",
        })

    # -------------------------------------------------------------
    # Scenario 7: Delayed Task (8 steps)
    # Severe mud and steep gradient drag down speed, spike load to 96%
    # -------------------------------------------------------------
    for i in range(8):
        records.append({
            "timestamp": next_time(),
            "machine_id": "CAT-797F-101",
            "operator_id": "OP-101",
            "engine_hours": round(8432.10 + i * 0.004, 2),
            "engine_rpm": 1980.0,
            "engine_load_pct": 95.5,
            "machine_speed_kmh": 6.8,  # Severely throttled due to mud/steep grade
            "fuel_used_l": round(78.40 + i * 0.55, 2),
            "idling_time_min": 12.0,
            "load_cycles": 15,
            "operating_state": "HAULING_LOADED",
            "seatbelt_status": "FASTENED",
            "proximity_distance_m": 35.0,
            "gps_zone": "RAMP_ACCESS_EAST",
            "working_condition": "MUDDY",
            "coolant_temp_c": 98.4,
            "hydraulic_oil_temp_c": 84.6,
            "fault_code": "TSK-DELAY-TRACTION",
            "task_id": "TSK-DEMO-07",
        })

    return records


def write_csv(filepath: Path, fieldnames: list[str], rows: list[dict]):
    """Write list of dicts to CSV file with UTF-8 encoding."""
    filepath.parent.mkdir(parents=True, exist_ok=True)
    with open(filepath, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def main():
    parser = argparse.ArgumentParser(description="ShiftGuard Synthetic Data Generator (Phase 1)")
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED, help="Deterministic random seed")
    parser.add_argument("--output-dir", type=str, default="data", help="Root data folder")
    parser.add_argument("--duration-hours", type=float, default=8.0, help="Shift duration for telemetry")
    parser.add_argument("--step-seconds", type=int, default=45, help="Seconds between telemetry points")
    args = parser.parse_args()

    print("=" * 70)
    print("ShiftGuard -- Synthetic Dataset Generator (Phase 1)")
    print(f"Random Seed: {args.seed} (Deterministic)")
    print("DISCLAIMER: All generated data is 100% synthetic for development/demo.")
    print("=" * 70)

    # Initialize deterministic RNG
    rng = random.Random(args.seed)
    base_dir = Path(args.output_dir)
    ensure_directories(base_dir)
    synthetic_dir = base_dir / "synthetic"

    # 1. Generate Task History
    print("\n[1/3] Generating task_history.csv...")
    tasks = generate_task_history(rng, num_tasks=150)
    task_fields = [
        "task_id",
        "machine_id",
        "operator_id",
        "task_type",
        "weather",
        "operator_skill",
        "machine_age_years",
        "estimated_time_min",
        "actual_time_min",
        "planned_start",
        "actual_start",
        "working_condition",
    ]
    task_csv_path = synthetic_dir / "task_history.csv"
    write_csv(task_csv_path, task_fields, tasks)
    print(f"  -> Generated {len(tasks)} tasks -> {task_csv_path}")

    # 2. Generate Telemetry History
    print(f"\n[2/3] Generating telemetry_history.csv ({args.duration_hours}h shift @ {args.step_seconds}s intervals)...")
    telemetry = generate_telemetry_history(
        rng, 
        tasks, 
        duration_hours=args.duration_hours, 
        step_seconds=args.step_seconds
    )
    telemetry_fields = [
        "timestamp",
        "machine_id",
        "operator_id",
        "engine_hours",
        "engine_rpm",
        "engine_load_pct",
        "machine_speed_kmh",
        "fuel_used_l",
        "idling_time_min",
        "load_cycles",
        "operating_state",
        "seatbelt_status",
        "proximity_distance_m",
        "gps_zone",
        "working_condition",
        "coolant_temp_c",
        "hydraulic_oil_temp_c",
        "fault_code",
        "task_id",
    ]
    telemetry_csv_path = synthetic_dir / "telemetry_history.csv"
    write_csv(telemetry_csv_path, telemetry_fields, telemetry)
    print(f"  -> Generated {len(telemetry)} telemetry records -> {telemetry_csv_path}")

    # 3. Generate Demo Telemetry
    print("\n[3/3] Generating demo_telemetry.csv (deterministic judging scenarios)...")
    demo_records = generate_demo_telemetry()
    demo_csv_path = synthetic_dir / "demo_telemetry.csv"
    write_csv(demo_csv_path, telemetry_fields, demo_records)
    print(f"  -> Generated {len(demo_records)} demo scenario records -> {demo_csv_path}")

    print("\n" + "=" * 70)
    print("SUCCESS: All 3 synthetic datasets generated cleanly.")
    print("=" * 70)


if __name__ == "__main__":
    main()
